package Model;

public enum Attributes {
	ACCELERATION, AGILITY, BALANCE, JUMPING_REACH, NATURAL_FITNESS, PACE, STAMINA, STRENGTH, AGGRESSION, ANTICIPATION,
	BRAVERY, COMPOSURE, CONCENTRATION, DECISIONS, DETERMINATION, FLAIR, LEADERSHIP, OFF_THE_BALL, POSITIONING, TEAMWORK,
	VISION, WORK_RATE, CORNERS, CROSSING, DRIBBLING, FINISHING, FIRST_TOUCH, FREE_KICK_TAKING, HEADING, LONG_SHOTS,
	LONG_THROWS, MARKING, PASSING, PENALTY_TAKING, TACKLING, TECHNIQUE

}
