package Model;

public enum goalkeeperAttributes {
	ACCELERATION, AGILITY, BALANCE, JUMPING_REACH, NATURAL_FITNESS, PACE, STAMINA, STRENGTH, AGGRESSION, ANTICIPATION,
	BRAVERY, COMPOSURE, CONCENTRATION, DECISIONS, DETERMINATION, FLAIR, LEADERSHIP, OFF_THE_BALL, POSITIONING, TEAMWORK,
	VISION, WORK_RATE, REFLEXES, ONE_ON_ONES, AERIAL_REACH, COMMAND_OF_AREA, COMMUNICATION, ECCENTRICITY, FIRST_TOUCH,
	HANDLING, KICKING, PASSING, PUNCHING, RUSHING_OUT, THROWING
}
